version: 2.1

executors:
  nodejs:
    docker:
      - image: cimg/node:18.13
    working_directory: ~/goodbye-rfc-2822-date-time

jobs:
  lint:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ checksum "package.json" }}-
      - run: yarn install --frozen-lockfile
      - run: yarn package
      - run: yarn lint
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - store_artifacts:
          path: web-ext-artifacts
      - store_artifacts:
          path: goodbye-rfc-2822-date-time.tar.gz

workflows:
  version: 2
  lint-deploy:
    jobs:
      - lint
