version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ checksum "package.json" }}-
      - run:
          name: Install yarn Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn package
      - run: yarn lint
      - store_artifacts:
          path: web-ext-artifacts
      - store_artifacts:
          path: goodbye-rfc-2822-date-time.tar.gz
